src/Entity/Simple.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SimpleRepository")
 */
class Simple
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_on;

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedOn(): ?\DateTimeInterface
    {
        return $this->created_on;
    }

    public function setCreatedOn(\DateTimeInterface $created_on): self
    {
        $this->created_on = $created_on;

        return $this;
    }
}

src/Form/SimpleType.php
<?php

namespace App\Form;

use App\Entity\Simple;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SimpleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('created_on')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Simple::class,
        ]);
    }
}

src/Controller/SimpleController.php
<?php

namespace App\Controller;

use App\Entity\Simple;
use App\Form\SimpleType;
use App\Repository\SimpleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/simple")
 */
class SimpleController extends Controller
{
    /**
     * @Route("/", name="simple_index", methods="GET")
     */
    public function index(SimpleRepository $simpleRepository): Response
    {
        return $this->render('simple/index.html.twig', ['simples' => $simpleRepository->findAll()]);
    }

    /**
     * @Route("/new", name="simple_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $simple = new Simple();
        $form = $this->createForm(SimpleType::class, $simple);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($simple);
            $em->flush();

            return $this->redirectToRoute('simple_index');
        }

        return $this->render('simple/new.html.twig', [
            'simple' => $simple,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="simple_show", methods="GET")
     */
    public function show(Simple $simple): Response
    {
        return $this->render('simple/show.html.twig', ['simple' => $simple]);
    }

    /**
     * @Route("/{id}/edit", name="simple_edit", methods="GET|POST")
     */
    public function edit(Request $request, Simple $simple): Response
    {
        $form = $this->createForm(SimpleType::class, $simple);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('simple_edit', ['id' => $simple->getId()]);
        }

        return $this->render('simple/edit.html.twig', [
            'simple' => $simple,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="simple_delete", methods="DELETE")
     */
    public function delete(Request $request, Simple $simple): Response
    {
        if ($this->isCsrfTokenValid('delete'.$simple->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($simple);
            $em->flush();
        }

        return $this->redirectToRoute('simple_index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/simple/_delete_form.html.twig
<form method="post" action="{{ path('simple_delete', {'id': simple.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ simple.id) }}">
    <button class="btn">Delete</button>
</form>

templates/simple/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/simple/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Simple{% endblock %}

{% block body %}
    <h1>Edit Simple</h1>

    {{ include('simple/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('simple_index') }}">back to list</a>

    {{ include('simple/_delete_form.html.twig') }}
{% endblock %}

templates/simple/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Simple index{% endblock %}

{% block body %}
    <h1>Simple index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Created_on</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for simple in simples %}
            <tr>
                <td>{{ simple.id }}</td>
                <td>{{ simple.name }}</td>
                <td>{{ simple.createdOn ? simple.createdOn|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('simple_show', {'id': simple.id}) }}">show</a>
                    <a href="{{ path('simple_edit', {'id': simple.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('simple_new') }}">Create new</a>
{% endblock %}

templates/simple/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Simple{% endblock %}

{% block body %}
    <h1>Create new Simple</h1>

    {{ include('simple/_form.html.twig') }}

    <a href="{{ path('simple_index') }}">back to list</a>
{% endblock %}

templates/simple/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Simple{% endblock %}

{% block body %}
    <h1>Simple</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ simple.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ simple.name }}</td>
            </tr>
            <tr>
                <th>Created_on</th>
                <td>{{ simple.createdOn ? simple.createdOn|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('simple_index') }}">back to list</a>

    <a href="{{ path('simple_edit', {'id': simple.id}) }}">edit</a>

    {{ include('simple/_delete_form.html.twig') }}
{% endblock %}